TeamSosik/Sosik_Member_Service

sosik-memberservice/build.gradle, sosik-memberservice/src/main/resources/application.yml
- [v]  버그 수정
YML을 잘못설정하여 났던 오류를 수정하였습니다. 그에 따라 h2의 다운그레이드도 필요하지 않아서 최신 버전으로 픽스하였습니다.
=> fix :  설정 변경

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/RequestMember.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/entity/Member.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/MemberRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
=> feat : 회원가입 기능 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/Result.java
- [X ]  기능 추가
Response DTO를 추가했습니다.
=> responseDTO 추가

sosik-memberservice/build.gradle, sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/interceptor/AuthInterceptor.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/interceptor/Authenticated.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/exception/ErrorCode.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/security/SecurityConfig.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/util/JwtTokenUtils.java, sosik-memberservice/src/main/resources/application.yml
- [ v ]  기능 추가
JWT 토큰로직을 구현했습니다.
=> feat : JWT 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/MemberEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java
- []  기능 추가
WeightEntity를 추가하였습니다.  MemberEntity와 관계성 매핑해주었습니다.
=> feat : WeightEntity추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/RedisConfig.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/RefreshTokenRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/RefreshTokenRepositoryImpl.java, sosik-memberservice/src/main/resources/application.yml
- [v]  기능 추가
Refresh토큰을 redis에 저장하기 위한 RedisConfig를 추가하였습니다. Redis는 Docker를 통해 추가하겠습니다.
=> feat: RedisConfig 추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/RedisConfig.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/RefreshTokenRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/RefreshTokenRepositoryImpl.java, sosik-memberservice/src/main/resources/application.yml
로그인 기능을 구현했습니다. 로그인은 accessToken과 RefreshToken을 발급합니다.
=> feat: 로그인 구현

sosik-memberservice/docker/docker-compose.yml, sosik-memberservice/src/main/resources/application.yml
=> refactor : YML 설정 변경

sosik-memberservice/src/main/resources/application-prod.yml
개발환경과 배포 환경의 YML을 분리하였습니다. Edit Configuration에서 변경하실 수 있습니다. 필요하다면 옵션을 바꾸셔도 됩니다.
사용방법
Edit Configuration -> Active profiles ->  -Dspring.profiles.active=dev
(입력이 안되어있으면 디폴트로 application.yml이 지정됩니다.)
=> feat : YML 환경 분리

sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/filter/JwtFilter.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestUpdate.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/exception/ErrorCode.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/Member.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/MemberEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/WeightRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
- [x]  환경 수정 및 기타
풀을 받지 않아 Conflict가 나왔던 코드들을 복구했습니다. 복구된 목록은 다음과 같습니다.
- WeightEntity
- Update 멤버
또한 Update 멤버는 컨벤션에 맞춰 DTO를 Request로 변경하였습니다.
=> fix : 구현된 코드 복구

sosik-memberservice/build.gradle, sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestFindPw.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/Mail.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/MemberEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MailService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/resources/application.yml
네이버 SMTP 서버를 이용하여 비밀번호 찾기를 구현하였습니다. 환경변수 설정은 다음 회의 때 설정해드리겠습니다.
=> feat : 비밀번호 찾기 로직 구현

sosik-memberservice/build.gradle, sosik-memberservice/docker/docker-compose.yml, sosik-memberservice/src/main/resources/application-prod.yml, sosik-memberservice/src/main/resources/application.yml
- 음식 데이터 서비스 작업을 위해 도커컴포즈에 음식 DB 서비스를 추가하였습니다.
- mysql 사용을 위해 관련 설정과 라이브러리를 추가하였습니다.
=> feat 도커컴포즈와 YML 환경에 mysql DB 추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/util/file/FileUtils.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/util/file/ResultFileStore.java
사용자가 이미지 등록 시 파일과 경로를 받을 수 있도록 구현하였습니다.
=> feat : 파일 업로드 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/ResponseAuth.java, sosik-memberservice/src/main/resources/application.yml
로그인 시 사용자 정보가 프론트에 전달될 수 있도록 토큰과 함께 전송하도록 구현하였습니다.
=> feat : 사용자 정보 전달

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/GetMemberDTO.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/GetWeight.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/MemberEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
- postman으로 잘 작동되는지 확인하지 못했습니다.
서비스 단위테스트는 완료하였지만 통합 테스트가 필요합니다.
- 생성날짜 컬럼을 사용못해 리스트로 Weight를 불러옵니다.
추후 Weight를 하나만 불러오는 로직이 필요할 거 같습니다.
=> Feat 회원 상세보기 기능 생성

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java
FE-BE연결을 위해 @CrossOrigin어노테이션을 주었습니다.
=> feat : 로그인 로그아웃 FE-BE연결

sosik-memberservice/src/main/java/com/example/sosikmemberservice/util/file/FileUtils.java
회원가입시 프로필이미지가 없어도 회원가입이 가능해집니다.
=> fix : 회원가입 버그 수정

sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestUpdate.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/GetWeight.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
goalWeight에서 targetWeight로 수정하였습니다.
=> #fix  WeightEntity컬럼 수정하였습니다.

sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestMember.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/GetWeight.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
=> feat 회원 등록 기능 수정

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/GetMember.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
- ## 🏷 작업 분류
- 네이밍 컨벤션에 따라 GetMemberDTO -> GetMember로 수정하였습니다.
=> fix 회원 조회 DTO명 수정

sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java
- 무게 엔터티의 goalWeight필드에서 targetWeight 필드로 변경에 따른 에러를 처리하였습니다.
=> fix 회원 엔터티 생성 로직 에러 수정

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestUpdate.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/exception/ErrorCode.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/Member.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/MemberEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/WeightRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/resources/application.yml, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
회원 정보수정 기능 Front랑 연결해서 리펙토링했습ㄴ니다.
=> #feat 회원 정보 수정 기능 리펙토링

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestWeight.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
=> Feat : 체중 기록 기능 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/filter/JwtFilter.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/GetWeight.java
마이페이지 프로필이미지와 몸무게를 전달합니다.
프로필 이미지 전달을 위해 controller를 추가하였습니다.
getweight타입을 변경하여 createAt이 'yyyy-mm-dd'형식으로 출력됩니다.
=> feat : 마이페이지 정보전달

sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/util/JwtTokenUtils.java
JWT 에 memberId 값을 추가하여 헤더에서 받을 수 있도록 구현하였습니다.
=> feat : api 게이트웨이에서 memberId 받기 구현

sosik-memberservice/build.gradle, sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/WebClientConfig.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/oauth/kakao/KakaoTokenJsonData.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/oauth/kakao/KakaoUserInfo.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/KakaoController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/oauth/kakao/RequestKakaoLogin.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/oauth/kakao/ResponseKakao.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/oauth/kakao/ResponseKakaoAccount.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/oauth/kakao/ResponseKakaoProfile.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/oauth/kakao/ResponseKakaoProperties.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/oauth/kakao/ResponseKakaoToken.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/oauth/kakao/ResponseKakaoUserInfo.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/OAuthService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/OAuthServiceImpl.java, sosik-memberservice/src/main/resources/application.yml
OAuth를 이용해서 카카오 로그인 할 수 있도록 구현했습니다.
=> feat : 카카오 로그인 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/MemberRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
프론트랑 연결완료, 컨트롤러 서비스 레포지토리 로직 추가
=> #feat 아이디 중복검사 기능 추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestUpdateMember.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/MemberEntity.java
회원정보수정 유효성검사 추가하고 닉네임 변경은 삭제했습니다.
=> #feat 회원정보수정 유효성 검사추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/SosikMemberserviceApplication.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/config/WebConfig.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/AuditingFields.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/security/SecurityConfig.java
추후에 Config 변경 가능성이 열려있어서 클래스를 분리해서 관리하고자 합니다. 추가로 H2가 시큐리티에 의해서 접근 안됐던 현상을 해결하였습니다.
=> refactor : Config 설정 추가

sosik-memberservice/src/main/resources/application-km.yml
=> #feat 개인 야물 파일 추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestWeight.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/exception/ErrorCode.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/resources/application-dahye.yml
현재 체중과 목표 체중 수정이 가능하게 구현하였습니다.
=> Feat : 나의 체중 수정 기능 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/OAuthServiceImpl.java, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
회원가입,회원정보 수정시 관리기간(주)이 계산되어 저장되게 수정
=> #refactor 회원가입,회원정보 수정 리펙토링

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/ResponseGetManagementData.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
일일 목표칼로리 기입시 참고할 수 있는 필요한 데이터를 가져오는 로직입니다!
=> #feat 일일 목표칼로리 기입에 필요한 데이터 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/WeightRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
오늘 체중을 기록했다면 중복으로 기록 못하게 프론트와 연결하여 구현하였습니다.
=> #feat 체중 중복기록 체크 구현

sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
=> #fix 체중기록 트랜젝션 추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestUpdateMember.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/request/RequestWeight.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/ResponseGetManagementData.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/oauth/kakao/ResponseMemberForOAuth.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/main/resources/application-minu.yml
=> refactor : 사용하지 않는 import 제거

sosik-memberservice/Dockerfile
=> feat: dockerFile

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java
memberId를 사용해서 nickname을 가져옵니다.
=> feat : 닉네임 가져오기

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/ResponseAuth.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/dto/response/ResponseGetManagementData.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/MemberEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java, sosik-memberservice/src/test/java/com/example/sosikmemberservice/service/MemberServiceImplTest.java
ServiceImpl에 builder패턴을 사용하였던것을 FactoryMethod 패턴으로 변경하였습니다! ## ***📜** 리뷰 요청사항*
=> refator 서비스단에 bulider패턴을 Factory매서드 패턴으로 변경

sosik-memberservice/build.gradle, sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/RefreshTokenRepository.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/repository/RefreshTokenRepositoryImpl.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberService.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
=> refactor : 로그아웃 코드 리팩터링

sosik-memberservice/build.gradle
- [x]  기능 추가
카프카 사용을 위해 의존성을 추가했습니다
=> feat: 카프카 의존성 추가

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java
=> feat 프로필이미지 불러오기

sosik-memberservice/src/main/java/com/example/sosikmemberservice/model/entity/WeightEntity.java, sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
무게추가 했을때 관리기간이 null로 들어가던 오류를 수정했습니다.
=> fix: 무게 추가 시 관리기간 오류 수정

sosik-memberservice/src/main/java/com/example/sosikmemberservice/controller/MemberController.java
=> rename uri 중복 삭제

sosik-memberservice/src/main/java/com/example/sosikmemberservice/service/MemberServiceImpl.java
프로필 이미지 없이 수정하는경우 전에 쓰던 프로필이미지가 들어가게 수정하였습니다!
=> fix: 프로필 이미지 수정 로직 변경

sosik-memberservice/src/main/resources/application-aws.yml
=> feat : 배포서버 YML
